teams = [
    "Baltimore",
    "Miami",
    "Chicago",
    "Cincinnati",
    "Detroit",
    "Minnesota",
    "Green Bay",
    "Carolina",
    "Los Angeles (LAC)",
    "Tennessee",
    "New England",
    "Atlanta",
    "San Francisco 49ers",
    "New York Giants (NYG)",
    "Indianapolis",
    "Pittsburgh",
    "Houston",
    "Denver",
    "Jacksonville",
    "Las Vegas",
    "Los Angeles (LAR)",
    "New Orleans",
    "Kansas City",
    "Buffalo",
    "Seattle",
    "Washington",
    "Dallas",
    "Arizona",
]
divisionsjson = [
    {"name": "AFC East"},
    {"name": "AFC West"},
    {"name": "AFC North"},
    {"name": "AFC South"},
    {"name": "NFC West"},
    {"name": "NFC East"},
    {"name": "NFC North"},
    {"name": "NFC South"},
]

# https://www.espn.com/nfl/teams
teamsjson = [
    {
        "name": "Baltimore Ravens",
        "Division": "AFC North",
        "Wins": 3,
        "Losses": 5,
        "Ties": 0,
    },
    {
        "name": "Miami Dolphins",
        "Division": "AFC East",
        "Wins": 2,
        "Losses": 7,
        "Ties": 0,
    },
    {
        "name": "Chicago Bears",
        "Division": "NFC North",
        "Wins": 5,
        "Losses": 3,
        "Ties": 0,
    },
    {
        "name": "Cincinnati Bengals",
        "Division": "AFC North",
        "Wins": 3,
        "Losses": 6,
        "Ties": 0,
    },
    {
        "name": "Detroit Lions",
        "Division": "NFC North",
        "Wins": 5,
        "Losses": 3,
        "Ties": 0,
    },
    {
        "name": "Minnesota Vikings",
        "Division": "NFC North",
        "Wins": 4,
        "Losses": 4,
        "Ties": 0,
    },
    {
        "name": "Green Bay Packers",
        "Division": "NFC North",
        "Wins": 5,
        "Losses": 2,
        "Ties": 1,
    },
    {
        "name": "Carolina Panthers",
        "Division": "NFC South",
        "Wins": 5,
        "Losses": 4,
        "Ties": 0,
    },
    {
        "name": "Los Angeles Rams (LAR)",
        "Division": "NFC West",
        "Wins": 6,
        "Losses": 2,
        "Ties": 0,
    },
    {
        "name": "Tennessee Titans",
        "Division": "AFC South",
        "Wins": 1,
        "Losses": 8,
        "Ties": 0,
    },
    {
        "name": "New England Patriots",
        "Division": "AFC East",
        "Wins": 7,
        "Losses": 2,
        "Ties": 0,
    },
    {
        "name": "Atlanta Falcons",
        "Division": "NFC South",
        "Wins": 3,
        "Losses": 5,
        "Ties": 0,
    },
    {
        "name": "San Francisco 49ers",
        "Division": "NFC West",
        "Wins": 6,
        "Losses": 3,
        "Ties": 0,
    },
    {
        "name": "New York Giants (NYG)",
        "Division": "NFC East",
        "Wins": 2,
        "Losses": 7,
        "Ties": 0,
    },
    {
        "name": "New York Jets (NYJ)",
        "Division": "AFC East",
        "Wins": 1,
        "Losses": 7,
        "Ties": 0,
    },
    {
        "name": "Indianapolis Colts",
        "Division": "AFC South",
        "Wins": 7,
        "Losses": 2,
        "Ties": 0,
    },
    {
        "name": "Pittsburgh Steelers",
        "Division": "AFC North",
        "Wins": 5,
        "Losses": 2,
        "Ties": 1,
    },
    {
        "name": "Houston Texans",
        "Division": "AFC South",
        "Wins": 3,
        "Losses": 5,
        "Ties": 0,
    },
    {
        "name": "Denver Broncos",
        "Division": "AFC West",
        "Wins": 7,
        "Losses": 2,
        "Ties": 0,
    },
    {
        "name": "Jacksonville Jaguars",
        "Division": "AFC South",
        "Wins": 5,
        "Losses": 3,
        "Ties": 0,
    },
    {
        "name": "Las Vegas Raiders",
        "Division": "AFC West",
        "Wins": 2,
        "Losses": 6,
        "Ties": 0,
    },
    {
        "name": "Los Angeles Chargers",
        "Division": "AFC West",
        "Wins": 6,
        "Losses": 3,
        "Ties": 0,
    },
    {
        "name": "New Orleans Saints",
        "Division": "NFC South",
        "Wins": 1,
        "Losses": 8,
        "Ties": 0,
    },
    {
        "name": "Kansas City Chiefs",
        "Division": "AFC West",
        "Wins": 3,
        "Losses": 5,
        "Ties": 0,
    },
    {
        "name": "Buffalo Bills",
        "Division": "AFC East",
        "Wins": 7,
        "Losses": 2,
        "Ties": 0,
    },
    {
        "name": "Seattle Seahawks",
        "Division": "NFC West",
        "Wins": 6,
        "Losses": 2,
        "Ties": 0,
    },
    {
        "name": "Washington Commanders",
        "Division": "NFC East",
        "Wins": 3,
        "Losses": 6,
        "Ties": 0,
    },
    {
        "name": "Dallas Cowboys",
        "Division": "NFC East",
        "Wins": 3,
        "Losses": 4,
        "Ties": 1,
    },
    {
        "name": "Arizona Cardinals",
        "Division": "NFC West",
        "Wins": 2,
        "Losses": 5,
        "Ties": 0,
    },
    {
        "name": "Philadelphia Eagles",
        "Division": "NFC East",
        "Wins": 6,
        "Losses": 2,
        "Ties": 0,
    },
    {
        "name": "Cleveland Browns",
        "Division": "AFC North",
        "Wins": 2,
        "Losses": 6,
        "Ties": 0,
    },
    {
        "name": "Tampa Bay Buccaneers",
        "Division": "NFC South",
        "Wins": 6,
        "Losses": 2,
        "Ties": 0,
    },
]
