teams = [
    "Baltimore",
    "Miami",
    "Chicago",
    "Cincinnati",
    "Detroit",
    "Minnesota",
    "Green Bay",
    "Carolina",
    "Los Angeles (LAC)",
    "Tennessee",
    "New England",
    "Atlanta",
    "San Francisco",
    "New York Giants (NYG)",
    "Indianapolis",
    "Pittsburgh",
    "Houston",
    "Denver",
    "Jacksonville",
    "Las Vegas",
    "Los Angeles (LAR)",
    "New Orleans",
    "Kansas City",
    "Buffalo",
    "Seattle",
    "Washington",
    "Dallas",
    "Arizona",
]
teamsjson = [
    {"Baltimore": "AFC North"},
    {"Miami": "AFC East"},
    {"Chicago": "NFC North"},
    {"Cincinnati": "AFC North"},
    {"Detroit": "NFC North"},
    {"Minnesota", "NFC North"},
    {"Green Bay": "NFC North"},
    {"Carolina": "NFC South"},
    {"Los Angeles (LAC)": "AFC West"},
    {"Tennessee": "AFC South"},
    {"New England": "AFC East"},
    {"Atlanta": "AFC South"},
    {"San Francisco": "NFC West"},
    {"New York Giants (NYG)": "NFC East"},
    {"Indianapolis": "NFC South"},
    {"Pittsburgh": "AFC North"},
    {"Houston": "AFC South"},
    {"Denver": "AFC West"},
    {"Jacksonville": "AFC South"},
    {"Las Vegas": "AFC West"},
    {"Los Angeles (LAR)": "NFC West"},
    {"New Orleans": "NFC South"},
    {"Kansas City": "AFC West"},
    {"Buffalo": "AFC East"},
    {"Seattle": "NFC West"},
    {"Washington": "NFC East"},
    {"Dallas": "NFC East"},
    {"Arizona": "NFC West"},
]
